CREATE TABLE customer (
    id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    olversion           integer NOT NULL DEFAULT 1,

    customernumber      varchar(10) UNIQUE NOT NULL,
    name                varchar(255) NOT NULL,
    forename            varchar(255) NOT NULL,
    bdate               date NOT NULL,
    salutation          varchar(5) NOT NULL,

    createdAt           date NOT NULL,
    changedAt           date NOT NULL
);

CREATE UNIQUE INDEX customer_number ON customer (customernumber);

CREATE TABLE address (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    olversion       integer NOT NULL DEFAULT 1,

    street          varchar(255) NOT NULL,
    housenumber     varchar(5) NOT NULL,
    citycode        varchar(5) NOT NULL,
    city            varchar(255)  NOT NULL,
    addressType     varchar(1) CONSTRAINT addressType_ckeck check(addressType in ('l', 'r')), -- l=lieferanten und r=rechnungsadresse
    customer        integer NOT NULL REFERENCES customer (id),

    createdAt       date NOT NULL,
    changedAt       date NOT NULL
);

CREATE TABLE product (
    id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    olversion           integer NOT NULL DEFAULT 1,

    price               NUMERIC(6,2) NOT NULL,
    productnumber       varchar(15) UNIQUE NOT NULL,
    description         TEXT,

    createdAt           date NOT NULL,
    changedAt           date NOT NULL
);

CREATE UNIQUE INDEX product_number ON product (productnumber);

CREATE TABLE shoporder (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    olversion       integer NOT NULL DEFAULT 1,

    customer        integer NOT NULL REFERENCES customer (id),
    ordernumber     varchar(15) UNIQUE NOT NULL,

    createdAt       date NOT NULL,
    changedAt       date NOT NULL
);

CREATE UNIQUE INDEX order_number ON shoporder (ordernumber);

CREATE TABLE shoporderitem (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    shoporder       integer NOT NULL REFERENCES shoporder (id),
    product         integer NOT NULL REFERENCES product (id),
    price           NUMERIC(6,2) NOT NULL,

    createdAt       date NOT NULL
);
